services:
  # ========================
  # Redis
  # ========================
  redis:
    container_name: redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s # check every 30 seconds
      timeout: 120s # allow 2 minutes for response
      retries: 3
      start_period: 20s # grace period after container starts

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5540 || exit 1"]
      interval: 60s # check every 1 minute
      timeout: 120s # allow 2 minutes
      retries: 3
      start_period: 20s

  # ========================
  # Backend
  # ========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s # check every 30 seconds
      timeout: 120s # allow 2 minutes for slow startups
      retries: 3
      start_period: 20s # grace period after container starts

  # ========================
  # Web (Frontend + NGINX)
  # ========================
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 60s # check every 1 minute
      timeout: 120s # allow 2 minutes
      retries: 3
      start_period: 20s

volumes:
  redis-data:
  redisinsight-data:

networks:
  app-network:
    driver: bridge
