version: "3.9"

services:
  # ========================
  # Redis
  # ========================
  redis:
    container_name: redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5540 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s

  # ========================
  # Backend
  # ========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  # ========================
  # Web (Frontend + NGINX)
  # ========================
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: web
    restart: unless-stopped
    env_file:
      - ./frontend/.env.production
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s

# ========================
# Volumes
# ========================
volumes:
  redis-data:
  redisinsight-data:

# ========================
# Network
# ========================
networks:
  app-network:
    driver: bridge
