services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --save 60 1000
      --save 300 10
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - app-network
    environment:
      # Superuser credentials
      POSTGRES_USER: ${POSTGRES_SUPERUSER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD:-postgres}
      # Application database credentials (passed to init script)
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      # Performance and locale settings
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.utf8"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_SUPERUSER:-postgres} -d postgres",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-dev-db.sh:/docker-entrypoint-initdb.d/01-init-dev-db.sh:ro
      - ./scripts/backup:/backup
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    shm_size: 128mb

volumes:
  redis-data:
    driver: local
    name: redis-data
  postgres-data:
    driver: local
    name: postgres-data

networks:
  app-network:
    driver: bridge
    name: app-network
