name: Backend Build

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-build.yml"

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript checks & Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Build backend
        run: npm run build

      # Upload backend build artifact
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: ./backend/dist

      - name: Backend build completed
        run: echo "Backend build completed successfully!"
