name: Full Stack CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  # ========================
  # Backend Build
  # ========================
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript checks & Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Build backend
        run: npm run build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: ./backend/dist

      - name: Backend build completed
        run: echo "Backend build completed successfully!"

  # ========================
  # Frontend Build
  # ========================
  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-build
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: ESLint check
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Build frontend
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist

      - name: Frontend build completed
        run: echo "Frontend build completed successfully!"

  # ========================
  # Docker Build & Push
  # ========================
  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: ./backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest ./frontend

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest
