name: Frontend Build

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-build.yml"

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: ESLint check
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Build frontend
        run: npm run build

      # Upload frontend build artifact
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist

      - name: Frontend build completed
        run: echo "Frontend build completed successfully!"
